# Generated by Django 5.2.1 on 2025-05-19 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(blank=True, null=True)),
                ("category_title", models.CharField(max_length=300, unique=True)),
                ("category_description", models.CharField(max_length=300)),
                ("category_number", models.IntegerField(unique=True)),
            ],
            options={
                "db_table": '"to_do_data"."categories"',
            },
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(blank=True, null=True)),
                ("task_title", models.CharField(max_length=300, unique=True)),
                ("task_description", models.CharField(max_length=300)),
                ("task_status", models.BooleanField(default=False)),
            ],
            options={
                "db_table": '"to_do_data"."tasks"',
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(blank=True, null=True)),
                ("username", models.CharField(max_length=150, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("surname", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("hashed_password", models.CharField(max_length=255)),
            ],
            options={
                "db_table": '"to_do_data"."user_data"',
            },
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(blank=True, null=True)),
                ("project_title", models.CharField(max_length=300, unique=True)),
                ("project_description", models.CharField(max_length=300)),
                (
                    "project_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="projects",
                        to="app.categories",
                    ),
                ),
            ],
            options={
                "db_table": '"to_do_data"."projects"',
            },
        ),
        migrations.CreateModel(
            name="TasksAssociation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(blank=True, null=True)),
                ("is_done", models.BooleanField(default=False)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_links",
                        to="app.projects",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_links",
                        to="app.tasks",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_assignments",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "db_table": '"to_do_data"."tasks_association"',
                "unique_together": {("project", "task", "user")},
            },
        ),
    ]
